### ISSUE TITLE
blender2.9.3 I can't install

### ISSUE THREAD

**Issue by zingcok** [Upliner/CharMorph#11]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/115346366/194700384-c03e7e45-f326-42bf-81bd-644b3614a3c4.png">

**Comment by Upliner** [comment]
Hmm I see that for some reason directory name is CharMorph-0.3.1-rc1, you should rename it to CharMorph

**Comment by Upliner** [comment]
Closing for now. Let me know if my solution doesn't work.
