### ISSUE TITLE
NO CHARACTER LIBRARY SECTION 

### ISSUE THREAD

**Issue by chrisvjaxson** [Upliner/CharMorph#20]
I don't have the option of making a character or even selecting a character gender

**Comment by Hopefullyidontgetbanned** [comment]
Have you downloaded the latest release? Check if you see the data folder in the add-ons' folder location

**Comment by chrisvjaxson** [comment]
Okay I see what you're talking about there was an updated code to install. Thank you

**Comment by Hopefullyidontgetbanned** [comment]
I guess you can close it now then
