### ISSUE TITLE
Blender 4 compatibility

### ISSUE THREAD

**Issue by mineralghost** [Upliner/CharMorph#21]
![Imagen de WhatsApp 2023-11-20 a las 17 05 43_d8573f22](https://github.com/Upliner/CharMorph/assets/151572664/ee9074ac-2786-4a06-8f15-338413d4c08d)

(sorry for bad image quality)

Whenever i use the Add rig function i get the image above. I have rigify installed. I tried with all the 4 models i have available and none of them work properly.

**Comment by Upliner** [comment]
Blender 4 compatibility is a real issue so reopening it

**Comment by Hopefullyidontgetbanned** [comment]
I should note that Particle Hair is broken for 4.0.

`bpy.data.window_managers["WinMan"].charmorph_ui.base_model = 'mb_female'`
`bpy.context.space_data.shading.type = 'WIREFRAME'`
`bpy.context.space_data.shading.type = 'SOLID'`
`bpy.data.window_managers["WinMan"].charmorph_ui.hair_style = 'symmetric1'`
`Python: Traceback (most recent call last):
  File "C:\Users\Hope\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\CharMorph-master\hair.py", line 269, in execute
    bpy.ops.particle.copy_particle_systems(override, remove_target_particles=False, use_active=True)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported`

**Comment by Hopefullyidontgetbanned** [comment]
> Issues seem to be fixed (rig and hair). If no other issues are found I gonna close this and make new CharMorph release.

Characters need to be manually converted but besides that everything works except inverting the preserve volume modifier
<img width="346" alt="image" src="https://github.com/Upliner/CharMorph/assets/45346421/02f8b2f4-7fc9-492b-860f-edb7fd90356e">

**Comment by Upliner** [comment]
Ahh it got inverted again! OK I'll take a look

**Comment by Hopefullyidontgetbanned** [comment]
doesn't seem to fixed

**Comment by Upliner** [comment]
> Characters need to be manually converted but besides that everything works except inverting the preserve volume modifier
OK, fixed it

**Comment by Hopefullyidontgetbanned** [comment]
I believe this can be closed now

**Comment by Hopefullyidontgetbanned** [comment]
Seems like this was a mistake @Upliner 
Character editing still throws errors
<img width="1583" alt="image" src="https://github.com/Upliner/CharMorph/assets/45346421/d839debb-ac5e-4fb4-bbe8-3820e87b6bdc">
