### ISSUE TITLE
Unable to create rig unless set to "Metarig only"

### ISSUE THREAD

**Issue by thelabcat** [Upliner/CharMorph#24]
As stated, unless I have "Metarig only" checked under Rig -> Rigify settings, I cannot add a rig, directly or in finalization. I get this error:
![charmorph_error](https://github.com/Upliner/CharMorph/assets/53358500/34376864-8b0e-497b-a9cb-3cd5083e315b)
This makes the addon pretty useless, as with the "Metarig only" option checked, the rig cannot deform the character at all. Blender 4.0.2.

**Comment by Hopefullyidontgetbanned** [comment]
have you used the latest version using `git clone --recursive`

**Comment by thelabcat** [comment]
It is version 0.3.2, but I did not use git to download it. I got it from [here](https://github.com/Upliner/CharMorph/releases/tag/v0.3.2).

**Comment by thelabcat** [comment]
Tried it, it works. Still says 0.3.2 tho. Thanks! Need to update that release, I think...
