### ISSUE TITLE
Mesh disappears when sculpting or texture painting

### ISSUE THREAD

**Issue by fvlasie** [Upliner/CharMorph#25]
Hello!

Thank you for the wonderful CharMorph module!

I would like to adjust the mesh ex post facto with sculpting to make a fantasy character but when I switch to Sculpt Mode the body mesh disappears and all I can see is the arms and eyelashes. The same thing happens when switching to Texture Paint Mode.

I am using the reom mesh in Blender 4.1.

P.S. I have finalized the mesh before attempting either sculpting or painting.

**Comment by Hopefullyidontgetbanned** [comment]
Go to edit mode and use alt + h to unhide all geometry

**Comment by fvlasie** [comment]
That did it! Thank you!
