### ISSUE TITLE
New character Antonia not rendering in Cycles

### ISSUE THREAD

**Issue by shankarsivarajan** [Upliner/CharMorph#3]
It works fine with Eevee (or the Look Dev mode), but when I switch to Cycles, I get the message "Loading Render Kernels: This can take a few minutes the first time," and it freezes indefinitely. The older MB-Lab characters continue to work correctly. I'm using the release version v0.2.5b.

Also, the "Adult Mode" setting doesn't have any effect on the Antonia model. Instead of the unsightly black texture used on the MB-Lab models, I suggest including the underwear assets you've created, and hiding them if "Adult Mode" is enabled.

**Comment by Upliner** [comment]
> Also, the "Adult Mode" setting doesn't have any effect on the Antonia model. Instead of the unsightly black texture used on the MB-Lab models, I suggest including the underwear assets you've created, and hiding them if "Adult Mode" is enabled.

It's exactly what I'm done. Everything works like this for me.

> It works fine with Eevee (or the Look Dev mode), but when I switch to Cycles, I get the message "Loading Render Kernels: This can take a few minutes the first time," and it freezes indefinitely. The older MB-Lab characters continue to work correctly. I'm using the release version v0.2.5b.

Strange. I can't reproduce this too.

**Comment by shankarsivarajan** [comment]
Okay, it renders correctly on the CPU _and_ on CUDA. The problem is only on OptiX. Maybe just letting the kernels over as long as it takes will fix it.

Regarding the much more minor problem, I'm on Blender 2.93.1, on Windows.

I get the following error when I import any character (even the MB-Lab ones): 
`Python: Traceback (most recent call last):`
  `File "C:\Users\Shankar Sivarajan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\CharMorph\library.py", line 400, in execute`
    `morphing.create_charmorphs(obj)`
` File "C:\Users\Shankar Sivarajan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\CharMorph\morphing.py", line 393, in create_charmorphs`
`m.create_charmorphs_L2()`
` File "C:\Users\Shankar Sivarajan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\CharMorph\morphing.py", line 324, in create_charmorphs_L2`
`[prefixed_prop("prop_", self.morph_prop(k, v)) for k, v in self.morphs_l2.items()] +`	
`File "C:\Users\Shankar Sivarajan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\CharMorph\morphing.py", line 324, in <listcomp>`
`[prefixed_prop("prop_", self.morph_prop(k, v)) for k, v in self.morphs_l2.items()] +`
`File "C:\Users\Shankar Sivarajan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\CharMorph\morphing.py", line 55, in prefixed_prop`
`return (prefix + prop[1]["name"], prop)`
`TypeError: '_PropertyDeferred' object is not subscriptable`
`location: <unknown location>:-1`
(with some lines indented where you'd expect. Those whitespaces aren't getting copied properly.)

(I got this error for a few other addons when I upgraded to 2.93.)

The error doesn't seem to do have any adverse effect with the other models. Looking up the error message, I found [this](https://github.com/nutti/Screencast-Keys/issues/45), where a suggestion that seems to work is a syntax change from `name = someProperty(...)` to `name: someProperty(...)`.

**Comment by Upliner** [comment]
> Okay, it renders correctly on the CPU _and_ on CUDA. The problem is only on OptiX. Maybe just letting the kernels load over as long as it takes will fix it. EDIT: It did!

Seems to be a bug in Cycles. I think you should file a bug report to them. I can't check it since I don't have Nvidia GPU.

> TypeError: '_PropertyDeferred' object is not subscriptable

This problem seems to happen only on 2.93. I'll take a look at it.

**Comment by Upliner** [comment]
Morphing error is fixed by this commit
https://github.com/Upliner/CharMorph/commit/e26ac3aed4a427eb9a3e647e73a590dc2f70bf85

**Comment by shankarsivarajan** [comment]
It's working perfectly now. Thank you!
