### ISSUE TITLE
It take long time to process each step

### ISSUE THREAD

**Issue by DENG-XC** [Upliner/CharMorph#31]
https://github.com/user-attachments/assets/0e358a40-959d-48d2-aebc-152efd85c3a6

hi, thank you for your hard to implement this amazing addon. but I have problem using this addon, whenever I use this addon, it take long time to loading.

blender version:  4.2 (same problem with 4.0.2)
charmorph version: 0.3.5

**Comment by Hopefullyidontgetbanned** [comment]
I assume you're using Subdivision Surface?
Morphing with a subdivision modifier usually has the effect of making it slower because it has to subdivide each time you move the sliders.

**Comment by DENG-XC** [comment]
> I assume you're using Subdivision Surface? Morphing with a subdivision modifier usually has the effect of making it slower because it has to subdivide each time you move the sliders.

Hi, thank you for your response. 
I did not use subdivision surface, I guess this addon is not compatible with blender 4.0+ , because I test it with blender 3.6, it works fine.


https://github.com/user-attachments/assets/bcebbee8-87b3-4741-a39e-52f66cbdcd4b

**Comment by Hopefullyidontgetbanned** [comment]
Strange, I have no issues on 4.2 with performance, what are your specs?

**Comment by DENG-XC** [comment]
> Strange, I have no issues on 4.2 with performance, what are your specs?

I guess there is conflict with some addons? I reinstall blender 4.2 with no addon, it works fine now.

**Comment by Hopefullyidontgetbanned** [comment]
that's strange, could re-enable other add-ons slowly to see if any of them conflict with Charmorph.

**Comment by DENG-XC** [comment]
> that's strange, could re-enable other add-ons slowly to see if any of them conflict with Charmorph.

strange, I reinstall all addon but charmorph works fine. no idea what cause this problem.  maybe blender preference setting cause this problem？（4.2 blender without import pervious blender preference setting and addon）

**Comment by Hopefullyidontgetbanned** [comment]
oh well it's seems like the problem fixed itself, maybe problem should be closed for now and can be re-opened if it happens again.
